// Generated by SolidPython 1.1.3 on 2023-10-12 19:07:09


union() {
	difference() {
		cube(size = [140, 50, 5]);
		translate(v = [5, 5, -0.5000000000]) {
			cube(size = [130, 40, 6]);
		}
		translate(v = [10, 25.0000000000, 2.5000000000]) {
			cylinder(h = 6, r = 2.0000000000);
		}
	}
	translate(v = [0, 17.5000000000, 1]) {
		difference() {
			cube(size = [100, 15, 4]);
			translate(v = [90, 7.5000000000, 2.0000000000]) {
				cylinder(h = 6, r = 2.0000000000);
			}
		}
	}
}